//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationTest.HrService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HrService.IPRS")]
    public interface IPRS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getFinancialReport", ReplyAction="http://tempuri.org/IPRS/getFinancialReportResponse")]
        NewMellatHR.HrService.FinancialReport[] getFinancialReport(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeImage", ReplyAction="http://tempuri.org/IPRS/getEmployeeImageResponse")]
        NewMellatHR.HrService.empImageData getEmployeeImage(string emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeSignature_ByShmEmz", ReplyAction="http://tempuri.org/IPRS/getEmployeeSignature_ByShmEmzResponse")]
        NewMellatHR.HrService.empSignatureData getEmployeeSignature_ByShmEmz(int SGN_115, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeSignature", ReplyAction="http://tempuri.org/IPRS/getEmployeeSignatureResponse")]
        NewMellatHR.HrService.empSignatureData getEmployeeSignature(string emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeSalaryGroup", ReplyAction="http://tempuri.org/IPRS/getEmployeeSalaryGroupResponse")]
        NewMellatHR.HrService.empSalaryData[] getEmployeeSalaryGroup(int fromIdx, int number, string vazKhedmatIdStr, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeSalary", ReplyAction="http://tempuri.org/IPRS/getEmployeeSalaryResponse")]
        NewMellatHR.HrService.empSalaryData getEmployeeSalary(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeSpecGroup", ReplyAction="http://tempuri.org/IPRS/getEmployeeSpecGroupResponse")]
        NewMellatHR.HrService.empSpecData[] getEmployeeSpecGroup(int fromIdx, int number, string vazKhedmatIdStr, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeTotalWork", ReplyAction="http://tempuri.org/IPRS/getEmployeeTotalWorkResponse")]
        NewMellatHR.HrService.empWorkHistoryData getEmployeeTotalWork(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeSpec", ReplyAction="http://tempuri.org/IPRS/getEmployeeSpecResponse")]
        NewMellatHR.HrService.empSpecData getEmployeeSpec(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeCell", ReplyAction="http://tempuri.org/IPRS/getEmployeeCellResponse")]
        System.Nullable<decimal> getEmployeeCell(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeCellGroup", ReplyAction="http://tempuri.org/IPRS/getEmployeeCellGroupResponse")]
        NewMellatHR.HrService.empCellData[] getEmployeeCellGroup(string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getChartKind", ReplyAction="http://tempuri.org/IPRS/getChartKindResponse")]
        NewMellatHR.HrService.ChartKindData[] getChartKind(int fromIdx, int number, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getChartKind_RecCount", ReplyAction="http://tempuri.org/IPRS/getChartKind_RecCountResponse")]
        int getChartKind_RecCount(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getRecruitmentStatusKind", ReplyAction="http://tempuri.org/IPRS/getRecruitmentStatusKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getRecruitmentStatusKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getOstanKind", ReplyAction="http://tempuri.org/IPRS/getOstanKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getOstanKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getCityKind", ReplyAction="http://tempuri.org/IPRS/getCityKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getCityKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getJobTitleKind", ReplyAction="http://tempuri.org/IPRS/getJobTitleKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getJobTitleKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getIDN_112Kind", ReplyAction="http://tempuri.org/IPRS/getIDN_112KindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getIDN_112Kind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getIDN_113Kind", ReplyAction="http://tempuri.org/IPRS/getIDN_113KindResponse")]
        NewMellatHR.HrService.IDN113KindData[] getIDN_113Kind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEduLevelKind", ReplyAction="http://tempuri.org/IPRS/getEduLevelKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getEduLevelKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getFieldKind", ReplyAction="http://tempuri.org/IPRS/getFieldKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getFieldKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getNoePostKind", ReplyAction="http://tempuri.org/IPRS/getNoePostKindResponse")]
        NewMellatHR.HrService.LoanConditionsData[] getNoePostKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getMostamaryInfo", ReplyAction="http://tempuri.org/IPRS/getMostamaryInfoResponse")]
        NewMellatHR.HrService.MostamariData getMostamaryInfo(decimal MostamariCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeePassedCourses", ReplyAction="http://tempuri.org/IPRS/getEmployeePassedCoursesResponse")]
        NewMellatHR.HrService.PassedCoursesData[] getEmployeePassedCourses(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getVazKhedmat_ForLoan", ReplyAction="http://tempuri.org/IPRS/getVazKhedmat_ForLoanResponse")]
        NewMellatHR.HrService.NeedToLoanControl getVazKhedmat_ForLoan(decimal NationalCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getArzeshyabi", ReplyAction="http://tempuri.org/IPRS/getArzeshyabiResponse")]
        NewMellatHR.HrService.ArzeshyabiData[] getArzeshyabi(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getEmployeeBoss", ReplyAction="http://tempuri.org/IPRS/getEmployeeBossResponse")]
        NewMellatHR.HrService.employeeBossData getEmployeeBoss(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/get_ComHistory", ReplyAction="http://tempuri.org/IPRS/get_ComHistoryResponse")]
        NewMellatHR.HrService.ComHistory[] get_ComHistory(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/get_EduHistory", ReplyAction="http://tempuri.org/IPRS/get_EduHistoryResponse")]
        NewMellatHR.HrService.EduHistory[] get_EduHistory(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/get_WorkHistory", ReplyAction="http://tempuri.org/IPRS/get_WorkHistoryResponse")]
        NewMellatHR.HrService.WorkHistory[] get_WorkHistory(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/get_EnfesalHistory", ReplyAction="http://tempuri.org/IPRS/get_EnfesalHistoryResponse")]
        NewMellatHR.HrService.EnfesalHistory[] get_EnfesalHistory(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/get_NoWorkHistory", ReplyAction="http://tempuri.org/IPRS/get_NoWorkHistoryResponse")]
        NewMellatHR.HrService.NoWorkHistory[] get_NoWorkHistory(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/get_IsarHistory", ReplyAction="http://tempuri.org/IPRS/get_IsarHistoryResponse")]
        NewMellatHR.HrService.IsarHistory[] get_IsarHistory(decimal emplCode, string Mode, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getVazKhedmatKind", ReplyAction="http://tempuri.org/IPRS/getVazKhedmatKindResponse")]
        NewMellatHR.HrService.VazKhedmat[] getVazKhedmatKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getHozehKind", ReplyAction="http://tempuri.org/IPRS/getHozehKindResponse")]
        NewMellatHR.HrService.hozehData[] getHozehKind(string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getVazKhedmat_Changes", ReplyAction="http://tempuri.org/IPRS/getVazKhedmat_ChangesResponse")]
        NewMellatHR.HrService.VazKhedmat_Changes[] getVazKhedmat_Changes(string Mode, int RowId, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPRS/getVazKhedmatAllPrs", ReplyAction="http://tempuri.org/IPRS/getVazKhedmatAllPrsResponse")]
        NewMellatHR.HrService.VazKhedmatAllPrs[] getVazKhedmatAllPrs(int fromIdx, int number, string Mode, string userName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPRSChannel : ConsoleApplicationTest.HrService.IPRS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PRSClient : System.ServiceModel.ClientBase<ConsoleApplicationTest.HrService.IPRS>, ConsoleApplicationTest.HrService.IPRS {
        
        public PRSClient() {
        }
        
        public PRSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PRSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PRSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PRSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NewMellatHR.HrService.FinancialReport[] getFinancialReport(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getFinancialReport(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empImageData getEmployeeImage(string emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeImage(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empSignatureData getEmployeeSignature_ByShmEmz(int SGN_115, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeSignature_ByShmEmz(SGN_115, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empSignatureData getEmployeeSignature(string emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeSignature(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empSalaryData[] getEmployeeSalaryGroup(int fromIdx, int number, string vazKhedmatIdStr, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeSalaryGroup(fromIdx, number, vazKhedmatIdStr, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empSalaryData getEmployeeSalary(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeSalary(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empSpecData[] getEmployeeSpecGroup(int fromIdx, int number, string vazKhedmatIdStr, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeSpecGroup(fromIdx, number, vazKhedmatIdStr, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empWorkHistoryData getEmployeeTotalWork(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeTotalWork(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empSpecData getEmployeeSpec(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeSpec(emplCode, Mode, userName, Password);
        }
        
        public System.Nullable<decimal> getEmployeeCell(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeCell(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.empCellData[] getEmployeeCellGroup(string Mode, string userName, string Password) {
            return base.Channel.getEmployeeCellGroup(Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.ChartKindData[] getChartKind(int fromIdx, int number, string userName, string Password) {
            return base.Channel.getChartKind(fromIdx, number, userName, Password);
        }
        
        public int getChartKind_RecCount(string userName, string Password) {
            return base.Channel.getChartKind_RecCount(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getRecruitmentStatusKind(string userName, string Password) {
            return base.Channel.getRecruitmentStatusKind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getOstanKind(string userName, string Password) {
            return base.Channel.getOstanKind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getCityKind(string userName, string Password) {
            return base.Channel.getCityKind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getJobTitleKind(string userName, string Password) {
            return base.Channel.getJobTitleKind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getIDN_112Kind(string userName, string Password) {
            return base.Channel.getIDN_112Kind(userName, Password);
        }
        
        public NewMellatHR.HrService.IDN113KindData[] getIDN_113Kind(string userName, string Password) {
            return base.Channel.getIDN_113Kind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getEduLevelKind(string userName, string Password) {
            return base.Channel.getEduLevelKind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getFieldKind(string userName, string Password) {
            return base.Channel.getFieldKind(userName, Password);
        }
        
        public NewMellatHR.HrService.LoanConditionsData[] getNoePostKind(string userName, string Password) {
            return base.Channel.getNoePostKind(userName, Password);
        }
        
        public NewMellatHR.HrService.MostamariData getMostamaryInfo(decimal MostamariCode, string Mode, string userName, string Password) {
            return base.Channel.getMostamaryInfo(MostamariCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.PassedCoursesData[] getEmployeePassedCourses(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeePassedCourses(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.NeedToLoanControl getVazKhedmat_ForLoan(decimal NationalCode, string Mode, string userName, string Password) {
            return base.Channel.getVazKhedmat_ForLoan(NationalCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.ArzeshyabiData[] getArzeshyabi(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getArzeshyabi(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.employeeBossData getEmployeeBoss(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.getEmployeeBoss(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.ComHistory[] get_ComHistory(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.get_ComHistory(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.EduHistory[] get_EduHistory(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.get_EduHistory(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.WorkHistory[] get_WorkHistory(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.get_WorkHistory(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.EnfesalHistory[] get_EnfesalHistory(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.get_EnfesalHistory(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.NoWorkHistory[] get_NoWorkHistory(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.get_NoWorkHistory(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.IsarHistory[] get_IsarHistory(decimal emplCode, string Mode, string userName, string Password) {
            return base.Channel.get_IsarHistory(emplCode, Mode, userName, Password);
        }
        
        public NewMellatHR.HrService.VazKhedmat[] getVazKhedmatKind(string userName, string Password) {
            return base.Channel.getVazKhedmatKind(userName, Password);
        }
        
        public NewMellatHR.HrService.hozehData[] getHozehKind(string userName, string Password) {
            return base.Channel.getHozehKind(userName, Password);
        }
        
        public NewMellatHR.HrService.VazKhedmat_Changes[] getVazKhedmat_Changes(string Mode, int RowId, string userName, string Password) {
            return base.Channel.getVazKhedmat_Changes(Mode, RowId, userName, Password);
        }
        
        public NewMellatHR.HrService.VazKhedmatAllPrs[] getVazKhedmatAllPrs(int fromIdx, int number, string Mode, string userName, string Password) {
            return base.Channel.getVazKhedmatAllPrs(fromIdx, number, Mode, userName, Password);
        }
    }
}
